// Verbatim from the Appendix in docs/requirements/phase-2c-appliance-cards.md
// — hand-written per appliance type, not generated live. Starting with the
// 5 types that already have real maintenance_rules content.
export const APPLIANCE_SUMMARIES: Record<string, string> = {
  roof: `Your roof has one job, but it's the job that matters most — keeping water out of your home, consistently, for decades. I'd recommend an annual inspection, and I'd pair that with regular gutter cleaning, since the two work together: clogged gutters push water back up under the shingles, which causes damage that has nothing to do with the roofing material itself. Most asphalt shingle roofs last 15 to 30 years depending on the material and your climate. Once you cross that 15-year mark, it's worth paying closer attention — granule loss, curling shingles, soft spots — not because something's necessarily wrong, but because that's the window where issues tend to start.`,

  hvac: `Of everything in this house, your HVAC system does the most constant, least visible work — and the filter is genuinely the single biggest factor in how well it holds up. I'd replace it every three months, more often if you have pets or allergies in the house, and schedule a professional tune-up annually on top of that. These systems typically last 15 to 25 years, though you'll usually notice some decline in efficiency starting around 10 to 12 years — that's expected wear, not a sign of failure.`,

  water_heater: `This is one appliance where I'd ask you to take the maintenance seriously, not just as a formality. The pressure relief valve is a genuine safety component, and I'd test it every year without fail. Beyond that, an annual tank flush will extend its working life, and the anode rod is worth checking starting around the two-to-three-year mark. Tank water heaters typically last 8 to 12 years — once you're past 8, it's worth watching for early signs of wear, like rust, leaks, or inconsistent heating.`,

  electrical_panel: `This is the kind of system that fails quietly, without much warning, which is exactly why I recommend a periodic professional inspection rather than waiting for a visible problem. Every two years is a reasonable interval. If your household's power demands have grown — an EV charger, a major addition — I'd move that inspection up rather than waiting for the next scheduled check. Panels generally last 25 to 40 years, so this isn't an urgent concern in most cases, but it's not one to overlook either.`,

  sump_pump: `I'd put this one in the "don't wait to find out" category. Test it directly — pour water into the pit and confirm it activates — rather than assuming it's working because it's been quiet, and I'd do that check twice a year, ideally ahead of your rainier season. An annual professional inspection of the pit, check valve, backup power, and alarm is worth the investment too. With regular maintenance, these last 10 to 15 years; without it, closer to 7 to 10. This is genuinely a safety-relevant appliance — if it fails, the result is active flooding, not a minor inconvenience.`,
};
